name: helpers
description: Helpers is a tool that allows you to convert repetitive and tedious statements into easy-to-read and intuitive statements.
version: 1.1.6
homepage: https://github.com/seel-channel/helpers

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.3"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0
